### PR TITLE
Use short array syntax

### PR DESCRIPTION
**Pull request by paulschreiber**
@kasparsd

### CODE REVIEW

**Comment by kasparsd** [comment]
This is an interesting one. I personally prefer the short array syntax but I wonder if we should stick to using WP core coding standards 100% just for the sake of having everything match how core does it. What are your thoughts on that?

**Comment by paulschreiber** [comment]
Maybe we should request a change to WPCS?
https://github.com/WordPress/WordPress-Coding-Standards/

**Comment by kasparsd** [comment]
This was discussed here a lot with a lot arguments from both sides https://make.wordpress.org/core/2019/07/12/php-coding-standards-changes/

**Comment by paulschreiber** [comment]
Hopefully they will reconsider.

**Pull request closed without merging**
